### ISSUE TITLE
Proposal: change the META function to a label

### ISSUE THREAD

**Issue by yuchi** [ipeychev/lfr-amd-loader#24]
Instead of

```js
(function META() {
    return { ...metaConfiguration };
});
```

we could go with labels:

```js
META: ({ ...metaConfiguration });
```

Both solutions are sensitive to dead-code elimination plugins that are emerging in babel-land.

**UPDATE:** Updated the syntax with the valid one (the parens around the object were missing).

**Comment by ipeychev** [comment]
Hey @yuchi,

What would be the benefits of such a change?

Thanks,

**Comment by yuchi** [comment]
Mostly succinctness and legibility.

**Comment by ipeychev** [comment]
I would have two questions here:

1) How do you imagine the exact syntax for the condition using the label to look like?

This is valid syntax:
```
(function META() {
    return {
        condition: {
            test: function() {
                return true;
            },
            trigger: 'nate'
        },
        path: 'nate.js'
    };
});
```

How exactly you plan to achieve something similar using a label, keeping in mind that you should isolate this part of the program from the rest?

2) Right now [extracting](https://github.com/ipeychev/lfr-module-config-generator/blob/master/lib/config-generator.js#L108) of the condition is trivial. How using a label would make both adding of a conditional configuration and parsing it more easily?

Thanks,

**Comment by yuchi** [comment]
#### Answer n. 1:

This is valid syntax as well. Labels are there only to label loop and be able to `break` outer loops.

```js
META: {
    condition: {
        test: function() {
            return true;
        },
        trigger: 'nate'
    },
    path: 'nate.js'
};
```

#### Answer n.2:

I don’t know very well the *jsstana* s-expression patterns, but looking at the code it has [no knowledge of labels](https://github.com/phadej/jsstana/search?utf8=%E2%9C%93&q=label), which is very bad anyway.

Babel instead [considers them](https://github.com/babel/babel/blob/91fb64eaf53c67a7ed7605aab71f8dcaa4d39ae2/packages/babel/src/types/retrievers.js#L53) correctly.

**Comment by ipeychev** [comment]
It is valid syntax? Have you tried to [validate](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=META%3A%20%7B%0A%20%20%20%20condition%3A%20%7B%0A%20%20%20%20%20%20%20%20test%3A%20function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20trigger%3A%20'nate'%0A%20%20%20%20%7D%2C%0A%20%20%20%20path%3A%20'nate.js'%0A%7D%3B) it or to run in in Node or a browser?

**Comment by yuchi** [comment]
Yes it is. It’s a label, a *goto*-like label. They work exclusively with `break` and `continue`.

```js
outer: while (true) {
  console.log('pre');

  while (true) {
    break outer;
  }

  console.log('post');
}
```

Run it and you’ll see that `post` is never print.

**Comment by ipeychev** [comment]
No, it was **not**.
What you posted previously was **not** a valid syntax, **there was a syntax error**. What you are positing now is **not** a META configuration.

What is your proposal at the end? To put the condition in while(true) statement or what?

A good proposal should be precisely made. If we are going to replace the existing syntax for META, we should replace it with something which makes sense. You are making the proposal and I am always open to discuss new ideas, but till now I haven't seen anything practical. Instead, you are trying to teach me how labels and goto work.

Thanks,

**Comment by yuchi** [comment]
That actual syntax, you’re right, is not valid. I was [fooled by a simpler case](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=META%3A%20%7B%20a%3Ab%20%7D%3B) that’s completely different in semantics (in that code there’s another `a` label followed by an ExpressionStatement alone, `b`).

My proposal would then become the following (which [validates](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&code=META%3A%20(%7B%0A%20%20%20%20condition%3A%20%7B%0A%20%20%20%20%20%20%20%20test%3A%20function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20trigger%3A%20'nate'%0A%20%20%20%20%7D%2C%0A%20%20%20%20path%3A%20'nate.js'%0A%7D)%3B)):

```js
META: ({
    condition: {
        test: function() {
            return true;
        },
        trigger: 'nate'
    },
    path: 'nate.js'
});
```

**Comment by ipeychev** [comment]
Okay, this looks better!
Let me see how hard would be to extract the configuration from it.

Thanks,

**Comment by natecavanaugh** [comment]
I like the idea as well :) I remember when we were first discussing the META aspect, I looked at the idea of a label, but hit that syntax issue, and didn't spend too much time digging into it, but I definitely think it's easier to read.

Thanks for the proposal @yuchi

**Comment by ipeychev** [comment]
Fixed here:
https://github.com/ipeychev/lfr-module-config-generator/issues/2
